# Generated by Django 4.0.1 on 2022-02-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_room_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='is_private',
            new_name='is_dm',
        ),
    ]
